name: "Rebase action"
description: "Rebases the branch if the checkbox is checked in PR Description"
inputs:
  GITHUB_TOKEN:
    description: Github token
    required: true
runs:
  using: "node12"
  main: "index.js"
