name: Rebase
on:
  pull_request:
    types: [edited]

jobs:
  rebase-job:
    runs-on: ubuntu-latest
    steps:
      - name: Rebase action
        id: rebase
        uses: srikarsams/sample-github-action@v1.3.28
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MESSAGE: "Rebase done successfully!"
