name: Rebase
on:
  pull_request:
    types: [opened, edited]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to rebase the branch
    steps:
      - name: Rebase actions
        id: rebase
        uses: srikarsams/sample-github-action@v1.3.12
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
