name: Rebase
on:
  pull_request:
    types: [opened, edited]

jobs:
  rebase-job:
    runs-on: ubuntu-latest
    steps:
      - name: Rebase actions
        id: rebase
        uses: srikarsams/sample-github-action@v1.3.17
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
