name: Rebase
on:
  pull_request:
    types: [opened, edited]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: srikarsams/sample-github-action@v1.3.11
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
